### ISSUE TITLE
Included IgnoresAccessChecksToAttribute can conflict with types from other assemblies

### ISSUE THREAD

**Issue by Alexejhero** [BepInEx/BepInEx.AssemblyPublicizer#5]
>   Submerged.AssemblyInfo.cs(13, 44): [CS0436] The type 'IgnoresAccessChecksToAttribute' in 'C:\Users\alexe\.nuget\packages\bepinex.assemblypublicizer.msbuild\0.2.0\contentFiles\cs\any\IgnoresAccessChecksToAttribute.cs' conflicts with the imported type 'IgnoresAccessChecksToAttribute' in 'MonoMod.Utils, Version=22.5.1.1, Culture=neutral, PublicKeyToken=null'. Using the type defined in 'C:\Users\alexe\.nuget\packages\bepinex.assemblypublicizer.msbuild\0.2.0\contentFiles\cs\any\IgnoresAccessChecksToAttribute.cs'.

BepInEx.Core imports MonoMod.Utils

**Comment by js6pak** [comment]
The problem here is that MonoMod shouldn't really expose `IgnoresAccessChecksToAttribute` as public.
I don't think there is any clean solution to this because you don't really know what referenced types there are from msbuild.

So the solution is either a msbuild property for not including IgnoresAccessChecksToAttribute or just the warning ignored with #pragma disable

**Comment by AlexejheroYTB** [comment]
There is an easy fix which is adding `<NoWarn>$(NoWarn);CS0436</NoWarn>` to the csproj, however since this warning happens by default with AssemblyPublicizer, and requiring each user to add that manually is not a good solution
